In [1]:
import numpy as np

In [ ]:
arr_1 = [1,2,3,4]

In [8]:
arr_full = np.full((2,3),6)

print('Full\n', arr_full)

Full
 [[6 6 6]
 [6 6 6]]


In [11]:
random = np.random.random((5,4))

print(random)

[[0.8210232  0.95960362 0.50152264 0.92203935]
 [0.35275033 0.54102545 0.07391483 0.5991116 ]
 [0.90583026 0.39993006 0.69801092 0.14317969]
 [0.38150046 0.30394245 0.62261581 0.37497767]
 [0.29689197 0.29601256 0.745798   0.67035183]]


In [15]:
sequence = np.arange(2,10,2)

print(sequence)

[2 4 6 8]


### Vector, Matrix, Tensor

In [ ]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrix = np.array([[1,2,3]
                   ,[4,5,6]])
print()
print(matrix)

In [8]:
tensor = np.array([[[[[1,2,3],[4,5,6]]],[[[6,7,8],[9,10,11]]]]])

print(tensor)

[[[[[ 1  2  3]
    [ 4  5  6]]]


  [[[ 6  7  8]
    [ 9 10 11]]]]]


### Array Properties


In [13]:
arr = np.array([
    [1,2,3],
    [4,5,True]
])

print("Shape: ",arr.shape )
print("Dimension: ",arr.ndim )
print("Size: ",arr.size )
print("Data type: ",arr.dtype )

Shape:  (2, 3)
Dimension:  2
Size:  6
Data type:  int64
