In [1]:
import numpy as np

## Numpy Array Operations 

### Indexing and Slicing

### Normal Array Slicing

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print("Basic Slicing: ", arr[2:7])

print('With Step: ', arr[1:9:2])

print('Reverse: ', arr[::-1])

print('Negative: ', arr[-3])

### 2D Array Slicing

In [2]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   ])

print('2D Array: \n', arr_2d)
print()
print('Specific Element: \n', arr_2d[1,2]) # row x column. here 1 is the 2nd row, and 2 is the third element of second row
print('Entire Row: \n', arr_2d[1])
print('Entire Column: \n', arr_2d[:,1]) # to get the entire second column

2D Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Specific Element: 
 6
Entire Row: 
 [4 5 6]
Entire Column: 
 [2 5 8]


## Sorting


In [ ]:
unsorted = np.array([3,2,4,5,1,6,8,7])

print('Sorted Array: ', np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],
                            [1,2],
                            [2,3]])
print('Sorted 2d Array by Column: \n', np.sort(arr_2d_unsorted, axis=0)) # axis=0 means sort by column

print('Sorted 2d Array by Row: \n', np.sort(arr_2d_unsorted, axis=1)) # axis=0 means sort by row

Sorted Array:  [1 2 3 4 5 6 7 8]
Sorted 2d Array by Column: 
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2d Array by Row: 
 [[1 3]
 [1 2]
 [2 3]]


In [11]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr[0])

[1 2 3]
