In [21]:
import numpy as np

## Adding and Removing Data

### Array Combine using np.concatenate()

In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))

print(combined)

[1 2 3 4 5 6]


### Array compatibility

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("Compatibility Shapes: ", a.shape == b.shape)

Compatibility Shapes:  False


### How to add a row to an existing array

In [19]:
original = np.array([[1,2],
                     [3,4]])

new_row = np.array([5,6])

with_new_row = np.vstack((original,new_row))
print('Original: \n', original)
print()
print('After adding new row: \n', with_new_row)

Original: 
 [[1 2]
 [3 4]]

After adding new row: 
 [[1 2]
 [3 4]
 [5 6]]


### How to add a column to an existing array

In [20]:
original = np.array([[1,2],
                     [3,4]])

new_col = np.array([[5 , 7],[6,8]])

with_new_col = np.hstack((original,new_col))

print('Original: \n', original)
print()
print('After adding new Column: \n', with_new_col)

Original: 
 [[1 2]
 [3 4]]

After adding new Column: 
 [[1 2 5 7]
 [3 4 6 8]]


### Deleting Data

In [23]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)

print('Array after deletion: ' ,deleted) # 3 is deleted

Array after deletion:  [1 2 4 5]
