## Numpy array and basics


In [2]:
import numpy as np 

### Creating array from list

In [8]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3],
                  [4,5,6]])
print(f"2D array: \n{arr_2d}")

1D array:  [1 2 3 4 5]
2D array: 
[[1 2 3]
 [4 5 6]]


### List vs numpy array

In [ ]:
py_list = [1,2,3]
print(f"Python list multiplication: {py_list*2}")

#numpy array
np_array = np.array([1,2,3]) #element wise multiplication
print(f"Numpy array multiplication: {np_array*2}")

import time
start = time.time()
py_list = [i*2 for i in range(100000000)]
print("\n List operation time: ", time.time() - start )


start2 = time.time()
np_array = np.arange(100000000)
print("\n Numpy array operation time: ", time.time() - start2 )

### creating array from scratch

In [ ]:
print('------Zeros Array-------')
zeros = np.zeros((3,4))
print("Zeros array: \n", zeros)

print('------Ones Array-------')
ones = np.ones((2,3))
print("Ones array: \n", ones)

print('------Constant Array-------')
full = np.full((2,2), 7)
print("Constant/Full array: \n", full)

print('------Random Array-------')
random = np.random.random((5,5)) #random values are always between 0s and 1s
print("Random array: \n", random)

print('------Sequence Array-------')

sequence = np.arange(0, 10, 2)
print("Sequence array: \n", sequence)


### Vector, Matrix and Tensor

In [ ]:
print()
print('------Vector Array-----------')
print()
vector = np.array([1,2,3,4])
print("Vector array: ", vector)

print()
print('------Matrix Array-----------')
print()
matrix= np.array([[1,2,3],
                  [4,5,6]]) #2d arrays are called matrix
print("Matrix array: \n", matrix)

print()
print('------Tensor Array-----------')
print()

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #tensor is actually multi dimensional array
print("Tensor array: \n", tensor)



------Vector Array-----------

Vector array:  [1 2 3 4]

------Matrix Array-----------

Matrix array: 
 [[1 2 3]
 [4 5 6]]

------Tensor Array-----------

Tensor array: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
