In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Advance operation with business examples: 

In [7]:
sales_data = np.array([
    [1, 1, 50, 500, 35], #Paradise Biriyani
    [2, 1, 55, 550, 50], #Beijing Bites
    [3, 3, 75, 1500, 65], #Pizza Hub
    [4, 1, 50, 500, 45] #Burger Point
])

print("==== Zomato sales analysis ==== ")
print('Sales data shape: ', sales_data.shape)

print('Sample data for 1st 3 restaurant: \n', sales_data[:,])

==== Zomato sales analysis ==== 
Sales data shape:  (4, 5)
Sample data for 1st 3 restaurant: 
 [[   1    1   50  500   35]
 [   2    1   55  550   50]
 [   3    3   75 1500   65]
 [   4    1   50  500   45]]


In [15]:
# Total sales per year

yearly_total = np.sum(sales_data[:, 1:], axis=0)
print(yearly_total)

# Minimum sales per restaurant 
min_sales = np.min(sales_data[1:, 2:], axis=1)
print('Minimum sales: \n', min_sales)

[   6  230 3050  195]
Minimum sales: 
 [50 65 45]
