## Numpy Array and basics



In [2]:
import numpy as np

## Creating Array from list

In [3]:
creating_array = np.array([1,2,3,4,5])
print(creating_array)

[1 2 3 4 5]


## Types of Array


#### 1D Array
A simple list of elements

In [4]:
arr_1d = np.array([1,2,3,4,5])
print('1D Array: \n', arr_1d)

1D Array: 
 [1 2 3 4 5]


#### 2D Array
An array of arrays like a table with rows and columns (matrix)

In [ ]:
arr_2d = np.array([[1,2,3], [4,5,6]])

print("2D Array: \n", arr_2d)


print()
#example 2:
arr_2dEx = np.array([[1,2,3,4],
                     [5,6,7,8],
                     [9,10,11,12]])
print("Eg 2: 2D Array : \n", arr_2dEx)

#### 3-D Array
Like a cube (multiple 2D arrays stacked together)

In [ ]:
arr_3D  = np.array([[[1,2,3], [4,5,6]],
                  [[7,8,9], [10,11,12]]])

print("3D Array: \n",arr_3D)   


### NumPy Arrays by Data Type

#### 1. Integer Array

Stores whole numbers.


In [22]:
arr = np.array([1, 2, 3, 4], dtype='int32')
print(arr)     # [1 2 3 4]
print(arr.dtype)  # we can check data types using dtype


[1 2 3 4]
int32


#### 2. Float Array

 Stores decimal numbers.

In [ ]:
arr = np.array([1.5, 2.7, 3.9])
print(arr)     # [1.5 2.7 3.9]
print(arr.dtype)  # float64


#### 3. String Array

Stores text.

In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr)       # ['apple' 'banana' 'cherry']
print(arr.dtype) # <U6 (string)


#### 4. Boolean Array

Stores True/False values.

In [ ]:
arr = np.array([True, False, True])
print(arr)       # [ True False  True]
print(arr.dtype) # bool
