In [3]:
import numpy as np

### Creating Array from scratch: 


#### np.zeros()

In [8]:
# Example of using np.zeros() to create a 3x3 array of zeros
example_zeros = np.zeros((3, 3))
print("3x3 array of zeros:\n", example_zeros)

3x3 array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### np.ones()

In [ ]:
# Create a 4x5 array of ones using np.ones()
Ones = np.ones((4, 5))
print("Ones array:\n", Ones)

#### np.full()

In [12]:
# Create a 3x4 array filled with the value 7 using np.full()
full_array = np.full((3, 4), 7) # it takes three argument: row column and the value(the number you want to fill the array with)
print("3x4 array filled with 7:\n", full_array)

3x4 array filled with 7:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


#### np.arange()

In [ ]:
# Example of using np.arange() to create an array with values from 0 to 9
arange_array = np.arange(10)
print("Array with values from 0 to 9:\n", arange_array)

#### np.linspace()


In [15]:
# Example of using np.linspace() to create an array of 5 evenly spaced values between 0 and 1
linspace_array = np.linspace(0, 1, 5)
print("Array of 5 evenly spaced values between 0 and 1:\n", linspace_array)

Array of 5 evenly spaced values between 0 and 1:
 [0.   0.25 0.5  0.75 1.  ]


#### np.random()

In [16]:
# np.random is a module, not a function. To generate random numbers, use functions like np.random.rand().
# Example: Create a 2x3 array of random floats between 0 and 1
random_array = np.random.rand(2, 3)
print("2x3 array of random floats between 0 and 1:\n", random_array)

2x3 array of random floats between 0 and 1:
 [[0.25009114 0.31678749 0.7042817 ]
 [0.36985299 0.14784346 0.05854951]]


#### np.sequence()

In [4]:
sequence = np.arange(0,10, 2)

print('Sequence array: \n', sequence)

Sequence array: 
 [0 2 4 6 8]


#### np.logspace()

In [ ]:
# Example of using np.logspace() to create an array of 5 values spaced evenly on a log scale between 10^1 and 10^3
logspace_array = np.logspace(1, 3, 5)
print("Array of 5 values spaced evenly on a log scale between 10^1 and 10^3:\n", logspace_array)