### Vector , Matrix and Tensor

In [1]:
import numpy as np

### Vector: 
normal arrays are called vector

In [ ]:
vector_array = np.array([1,2,3])
print('Vector: \n', vector_array)

### Matrix
2D Arrays are called matrix

In [ ]:
matrix = np.array([[1,2,3],
                   [4,5,6]])


print('Matrix: \n', matrix)

### Tensor
A tensor in NumPy (or in general math/ML) can have any number of dimensions

In [4]:
tensor = np.array([[[1,2,3],[4,5,6],
                    [7,8,9],[10,11,12]]])

print("Tensor: \n", tensor)

Tensor: 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
