In [2]:
import numpy as np

### Array Reshaping


In [ ]:
arr = np.arange(12)
print("original Array :", arr)



original Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### Reshape

In [ ]:
arr = np.arange(12)
reshaped = arr.reshape((3,4))
print("Reshaped: \n", reshaped)

#### Flatten

In [ ]:
arr = np.arange(12)
reshaped = arr.reshape((3,4))
print("Reshaped: \n", reshaped)
print()
flattened = reshaped.flatten()
print('Flattened: \n', flattened)

#### Ravel
returns view, instead of copy

In [13]:
arr = np.arange(12)
reshaped = arr.reshape(4,3)
raveled = reshaped.ravel()
print('Raveled: \n', arr)

raveled[0] = 100
print("After modifying raveled:")
print("Raveled:\n", raveled)
print("Reshaped:\n", reshaped)
print("Original arr:\n", arr) 

Raveled: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
After modifying raveled:
Raveled:
 [100   1   2   3   4   5   6   7   8   9  10  11]
Reshaped:
 [[100   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]
Original arr:
 [100   1   2   3   4   5   6   7   8   9  10  11]


#### Transpose
In NumPy, transpose is used to flip or swap the axes of an array.

In simple terms: it changes the rows into columns and columns into rows.

In [ ]:
arr = np.arange(12)
reshaped = arr.reshape((6,2))
print('Reshaped: \n', reshaped)
print()
transpose = reshaped.T
print('Transposed: \n', transpose)