In [1]:
import numpy as np

In [ ]:
'''Exercise 1

Create a 1D array of numbers from 5 to 25.'''

normal = np.arange(5,26)

print(normal)



[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [ ]:
'''Exercise 2

Make a 3x3 matrix filled with the number 9.'''

threexthree = np.full((3,3),9)
print(threexthree)

In [14]:
'''Exercise 3

Generate a 1D array of 8 random integers between 10 and 100.'''

dom1 = np.random.randint(10,101,size=8)
print(dom1)

[16 72 69 52 76 98 59 38]


In [ ]:
'''Exercise 4

Create a 4x4 array of random numbers (between 0 and 1) and print its:'''

random2 = np.random.rand(4,4)

print(random2)

print("Dimension: ", random2.ndim) 
print("Shape: ", random2.shape) 
print("Size: ", random2.size) 
print("Itemsize: ", random2.itemsize) 


In [5]:
'''Exercise 5

Create a linearly spaced array of 15 values between 0 and 10.'''

linearly = np.linspace(0,10,15)
print(linearly)



[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [6]:
'''Exercise 6

Create a 5x5 identity matrix using NumPy.'''

identity = np.eye(5)
print(identity)



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
'''Exercise 7

Generate a 2D array of shape (3, 4) with random integers between 1 and 50. Reshape it into (6, 2).'''

x2D = np.random.randint(1,50,size=(3,4))
print(x2D)
reshaped = x2D.reshape(6,2)
print("Reshaped: \n", reshaped)

[[26 25 30 18]
 [41 47 14  6]
 [13 49  9 21]]
Reshaped: 
 [[26 25]
 [30 18]
 [41 47]
 [14  6]
 [13 49]
 [ 9 21]]


In [ ]:
'''Exercise 8

Create an array of numbers from 1 to 12, reshape it into a 3x4 matrix, then flatten it using both ravel() and flatten(). Change one element in the ravel() result and check if the original array changes.'''

arr = np.arange(1,13)

reshaped = arr.reshape(3,4)

print('Reshaped: \n', reshaped)

flatten = reshaped.flatten()
print('Flattened: \n', flatten)


ravel = reshaped.ravel()
print('Ravel: \n', ravel)

print(reshaped)

In [9]:
'''Exercise 9

Make a 2x3 matrix and compute its transpose.'''

twobythree = np.random.rand(2,3)

print(twobythree)

transpose = twobythree.T
print('Transposed: \n', transpose)

[[0.35045587 0.57190249 0.59788021]
 [0.98538766 0.6442225  0.5926651 ]]
Transposed: 
 [[0.35045587 0.98538766]
 [0.57190249 0.6442225 ]
 [0.59788021 0.5926651 ]]


In [4]:
random_arr = np.random.randint(1,10,size=(5,2))

print(random_arr)

[[6 2]
 [9 2]
 [3 7]
 [5 4]
 [3 8]]
