In [1]:
import numpy as np

In [ ]:
'''Exercise 1

Create a 1D array of numbers from 5 to 25.'''

normal = np.arange(5,26)

print(normal)



[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [ ]:
'''Exercise 2

Make a 3x3 matrix filled with the number 9.'''

threexthree = np.full((3,3),9)
print(threexthree)

In [14]:
'''Exercise 3

Generate a 1D array of 8 random integers between 10 and 100.'''

dom1 = np.random.randint(10,101,size=8)
print(dom1)

[16 72 69 52 76 98 59 38]


In [ ]:
'''Exercise 4

Create a 4x4 array of random numbers (between 0 and 1) and print its:'''

random2 = np.random.rand(4,4)

print(random2)

print("Dimension: ", random2.ndim) 
print("Shape: ", random2.shape) 
print("Size: ", random2.size) 
print("Itemsize: ", random2.itemsize) 


In [ ]:
'''Exercise 5

Create a linearly spaced array of 15 values between 0 and 10.'''

linearly = np.linspace(0,10,15)
print(linearly)



In [ ]:
'''Exercise 6

Create a 5x5 identity matrix using NumPy.'''

identity = np.eye(5)
print(identity)



In [ ]:
'''Exercise 7

Generate a 2D array of shape (3, 4) with random integers between 1 and 50. Reshape it into (6, 2).'''

x2D = np.random.randint(1,50,size=(3,4))
print(x2D)
reshaped = x2D.reshape(6,2)
print("Reshaped: \n", reshaped)

In [ ]:
'''Exercise 8

Create an array of numbers from 1 to 12, reshape it into a 3x4 matrix, then flatten it using both ravel() and flatten(). Change one element in the ravel() result and check if the original array changes.'''

arr = np.arange(1,13)

reshaped = arr.reshape(3,4)

print('Reshaped: \n', reshaped)

flatten = reshaped.flatten()
print('Flattened: \n', flatten)


ravel = reshaped.ravel()
print('Ravel: \n', ravel)

print(reshaped)

In [ ]:
'''Exercise 9

Make a 2x3 matrix and compute its transpose.'''

twobythree = np.random.rand(2,3)

print(twobythree)

transpose = twobytwo.T
print('Transposed: \n', transpose)

[[0.6806518  0.5350495  0.12416187]
 [0.79232097 0.76514977 0.14705539]]
Transposed: 
 [[0.6806518  0.79232097]
 [0.5350495  0.76514977]
 [0.12416187 0.14705539]]
